require("config.configs")
require("config.keymaps")
require("config.autocmds")
require("config.treesitter")
require("config.lsp")
require("config.telescope")
require("config.signs")
require("config.miscelanea")
